services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    network_mode: host
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
